# Generated by Django 6.0.6 on 2026-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stint',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='stint',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='stint',
            name='car',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='stint',
            name='game',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stint',
            name='session_uuid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stint',
            name='track',
            field=models.CharField(max_length=100),
        ),
    ]
