# Generated by Django 6.0.6 on 2026-06-23 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_rename_start_time_stint_created_at_stint_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryLap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField()),
                ('lap_time', models.FloatField()),
                ('best_lap', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='telemetry.stint')),
            ],
        ),
    ]
