# Generated by Django 6.0.6 on 2026-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_telemetrylap'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrylap',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='telemetrylap',
            name='driver_slot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
