# Generated by Django 6.0.6 on 2026-06-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_telemetrylap_driver_name_telemetrylap_driver_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stint',
            name='track',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
